### ISSUE TITLE
subtitles from video container

### ISSUE THREAD

**Issue by vip12** [silentmurdock/whiteraven#3]
it's not documented, but it works
```
var _initSubtitle = function () {
                _AVPlay.startSubtitle({ path: "/dtv/temp/", streamID: 999, sync: 999, callback: function () { } });
            }
var amount = _AVPlay.getTotalNumOfStreamID(4);
_AVPlay.setStreamID(4, idSubtitle)
```

**Comment by silentmurdock** [comment]
Thank you for your comment, but this feature was not working with all supported TV types.

Earlier versions of White Raven used this built-in feature, but it did not work properly on some models. I think it was mainly the H-type that had problems. Also, the location, color and size of the subtitle could not be adjusted properly with the built-in feature. It didn't work on the Tizen either. So, I decided to write an own subtitle display routine.

**Comment by vip12** [comment]
> Thank you for your comment, but this feature was not working with all supported TV types.
> 
> Earlier versions of White Raven used this built-in feature, but it did not work properly on some models. I think it was mainly the H-type that had problems. Also, the location, color and size of the subtitle could not be adjusted properly with the built-in feature. It didn't work on the Tizen either. So, I decided to write an own subtitle display routine.

This function does not determine the type of subtitles, it returns only their text, but you need to do event handling, the text is returned in event 19 SUBTITLE

```
  _AVPlay.onEvent = _eventHandler;
var _eventHandler = function (type, data) {
                switch (type) {
                    // 19 SUBTITLE
                    case 19:
                            thisTextSubtitle(data)
                        }
```
